
find_program(DOXYGEN_EXE NAMES doxygen)
mark_as_advanced(DOXYGEN_EXE)
if (DOXYGEN_EXE)
  foreach (mode html latex man)
    string(TOUPPER ${mode} mode_upper)
    set(ENABLED_SECTIONS)
    set(EXCLUDE)
    set(GENERATE_LATEX NO)
    set(GENERATE_HTML NO)
    set(GENERATE_MAN NO)
    set(FILE_PATTERNS "*.cpp *.h *.c *.dox")
    set(GENERATE_${mode_upper} YES)
    if (GENERATE_HTML)
      set(ENABLED_SECTIONS "link_code link_examples link_internal")
    endif ()
    if (GENERATE_LATEX)
      set(FILE_PATTERNS "*.dox")
      set(ENABLED_SECTIONS "link_internal")
      set(EXCLUDE "${CMAKE_SOURCE_DIR}/doc/generated_examples ${CMAKE_SOURCE_DIR}/doc/example.dox ${CMAKE_SOURCE_DIR}/doc/diff_example.dox ${CMAKE_SOURCE_DIR}/doc/merge_example.dox")
    endif ()
    if (GENERATE_MAN)
      set(FILE_PATTERNS "cmd_*.dox")
      set(ENABLED_SECTIONS "link_internal")
    endif ()
    configure_file(${CMAKE_SOURCE_DIR}/conf/coopy_doxygen.conf.in
      ${CMAKE_BINARY_DIR}/coopy_doxygen_${mode}.conf IMMEDIATE)
    add_custom_target(${mode} COMMAND ${DOXYGEN_EXE} ${CMAKE_BINARY_DIR}/coopy_doxygen_${mode}.conf)
  endforeach ()
endif ()
