#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
	HX_CSTRING("/usr/lib/haxe/std/Lambda.hx"),
	HX_CSTRING("/usr/lib/haxe/std/List.hx"),
	HX_CSTRING("/usr/lib/haxe/std/cpp/_std/Std.hx"),
	HX_CSTRING("/usr/lib/haxe/std/cpp/_std/StringBuf.hx"),
	HX_CSTRING("/usr/lib/haxe/std/cpp/_std/haxe/ds/IntMap.hx"),
	HX_CSTRING("/usr/lib/haxe/std/cpp/_std/haxe/ds/StringMap.hx"),
	HX_CSTRING("/usr/lib/haxe/std/haxe/Log.hx"),
	HX_CSTRING("coopy/Alignment.hx"),
	HX_CSTRING("coopy/CellInfo.hx"),
	HX_CSTRING("coopy/Change.hx"),
	HX_CSTRING("coopy/Compare.hx"),
	HX_CSTRING("coopy/CompareFlags.hx"),
	HX_CSTRING("coopy/CompareTable.hx"),
	HX_CSTRING("coopy/Coopy.hx"),
	HX_CSTRING("coopy/CrossMatch.hx"),
	HX_CSTRING("coopy/Csv.hx"),
	HX_CSTRING("coopy/DiffRender.hx"),
	HX_CSTRING("coopy/HighlightPatch.hx"),
	HX_CSTRING("coopy/HighlightPatchUnit.hx"),
	HX_CSTRING("coopy/Index.hx"),
	HX_CSTRING("coopy/IndexItem.hx"),
	HX_CSTRING("coopy/IndexPair.hx"),
	HX_CSTRING("coopy/Mover.hx"),
	HX_CSTRING("coopy/Ordering.hx"),
	HX_CSTRING("coopy/Report.hx"),
	HX_CSTRING("coopy/SimpleCell.hx"),
	HX_CSTRING("coopy/SimpleTable.hx"),
	HX_CSTRING("coopy/SimpleView.hx"),
	HX_CSTRING("coopy/SparseSheet.hx"),
	HX_CSTRING("coopy/TableComparisonState.hx"),
	HX_CSTRING("coopy/TableDiff.hx"),
	HX_CSTRING("coopy/TableIO.hx"),
	HX_CSTRING("coopy/TableModifier.hx"),
	HX_CSTRING("coopy/TableText.hx"),
	HX_CSTRING("coopy/TableView.hx"),
	HX_CSTRING("coopy/Unit.hx"),
	HX_CSTRING("coopy/ViewedDatum.hx"),
	HX_CSTRING("coopy/Viterbi.hx"),
	HX_CSTRING("coopy/Workspace.hx"),
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
    HX_CSTRING("Lambda"),
    HX_CSTRING("List"),
    HX_CSTRING("Std"),
    HX_CSTRING("StringBuf"),
    HX_CSTRING("coopy.Alignment"),
    HX_CSTRING("coopy.CellInfo"),
    HX_CSTRING("coopy.Change"),
    HX_CSTRING("coopy.Compare"),
    HX_CSTRING("coopy.CompareFlags"),
    HX_CSTRING("coopy.CompareTable"),
    HX_CSTRING("coopy.Coopy"),
    HX_CSTRING("coopy.CrossMatch"),
    HX_CSTRING("coopy.Csv"),
    HX_CSTRING("coopy.DiffRender"),
    HX_CSTRING("coopy.HighlightPatch"),
    HX_CSTRING("coopy.HighlightPatchUnit"),
    HX_CSTRING("coopy.Index"),
    HX_CSTRING("coopy.IndexItem"),
    HX_CSTRING("coopy.IndexPair"),
    HX_CSTRING("coopy.Mover"),
    HX_CSTRING("coopy.Ordering"),
    HX_CSTRING("coopy.Report"),
    HX_CSTRING("coopy.SimpleCell"),
    HX_CSTRING("coopy.SimpleTable"),
    HX_CSTRING("coopy.SimpleView"),
    HX_CSTRING("coopy.SparseSheet"),
    HX_CSTRING("coopy.TableComparisonState"),
    HX_CSTRING("coopy.TableDiff"),
    HX_CSTRING("coopy.TableIO"),
    HX_CSTRING("coopy.TableModifier"),
    HX_CSTRING("coopy.TableText"),
    HX_CSTRING("coopy.TableView"),
    HX_CSTRING("coopy.Unit"),
    HX_CSTRING("coopy.ViewedDatum"),
    HX_CSTRING("coopy.Viterbi"),
    HX_CSTRING("coopy.Workspace"),
    HX_CSTRING("haxe.Log"),
    HX_CSTRING("haxe.ds.IntMap"),
    HX_CSTRING("haxe.ds.StringMap"),
#endif
 0 };
} // namespace hx
