IF (NOT CMAKE_JavaC_COMPILER_LOADED)
  SET(CMAKE_BASE_NAME g++)
  SET(CMAKE_JavaC_COMPILER "gcj")
  SET(CMAKE_JavaC_COMPILER_LOADED 1)


  IF(CMAKE_USER_MAKE_RULES_OVERRIDE)
    INCLUDE(${CMAKE_USER_MAKE_RULES_OVERRIDE})
  ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE)
  
  IF(CMAKE_USER_MAKE_RULES_OVERRIDE_JavaC)
    INCLUDE(${CMAKE_USER_MAKE_RULES_OVERRIDE_JavaC})
  ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE_JavaC)


  SET(CMAKE_JavaC_SOURCE_FILE_EXTENSIONS java)
  # SET(CMAKE_JavaC_LINKER_PREFERENCE 40)
  SET(CMAKE_JavaC_OUTPUT_EXTENSION ".o")
  SET(CMAKE_JavaC_OUTPUT_EXTENSION_REPLACE 1)
  SET(CMAKE_INCLUDE_FLAG_JavaC "-I")
  SET(CMAKE_JavaC_COMPILE_OBJECT "gcj  <CMAKE_SHARED_LIBRARY_JavaC_FLAGS>       <CMAKE_SHARED_LIBRARY_CREATE_JavaC_FLAGS>     <FLAGS> -o <OBJECT> -c <SOURCE> && objcopy -L '_ZGr8_\$\$_dummy' <OBJECT>")
  SET(CMAKE_JavaC_CREATE_SHARED_LIBRARY "gcj <LANGUAGE_COMPILE_FLAGS> <CMAKE_SHARED_LIBRARY_JavaC_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_JavaC_FLAGS> <CMAKE_SHARED_LIBRARY_SONAME_JavaC_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
  IF(NOT CMAKE_JavaC_LINK_EXECUTABLE)
    SET(CMAKE_JavaC_LINK_EXECUTABLE
      "<CMAKE_CXX_COMPILER> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>")
  ENDIF()

  SET(CMAKE_JavaC_COMPILER_ENV_VAR JAVAC_COMPILER)

  IF(NOT CMAKE_SHARED_LIBRARY_CREATE_JavaC_FLAGS)
    SET(CMAKE_SHARED_LIBRARY_CREATE_JavaC_FLAGS ${CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS})
  ENDIF(NOT CMAKE_SHARED_LIBRARY_CREATE_JavaC_FLAGS)

  IF(NOT CMAKE_SHARED_LIBRARY_JavaC_FLAGS)
    SET(CMAKE_SHARED_LIBRARY_JavaC_FLAGS ${CMAKE_SHARED_LIBRARY_C_FLAGS})
  ENDIF(NOT CMAKE_SHARED_LIBRARY_JavaC_FLAGS)

  IF(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_JavaC_FLAGS)
    SET(CMAKE_SHARED_LIBRARY_LINK_JavaC_FLAGS ${CMAKE_SHARED_LIBRARY_LINK_C_FLAGS})
  ENDIF(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_JavaC_FLAGS)

  IF(NOT CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG)
    SET(CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG ${CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG}) 
  ENDIF(NOT CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG)

  IF(NOT CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG_SEP)
    SET(CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG_SEP ${CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP})
  ENDIF(NOT CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG_SEP)

  IF(NOT CMAKE_SHARED_LIBRARY_RPATH_LINK_JavaC_FLAG)
    SET(CMAKE_SHARED_LIBRARY_RPATH_LINK_JavaC_FLAG ${CMAKE_SHARED_LIBRARY_RPATH_LINK_C_FLAG})
  ENDIF(NOT CMAKE_SHARED_LIBRARY_RPATH_LINK_JavaC_FLAG)

  IF(NOT DEFINED CMAKE_EXE_EXPORTS_JavaC_FLAG)
    SET(CMAKE_EXE_EXPORTS_JavaC_FLAG ${CMAKE_EXE_EXPORTS_C_FLAG})
  ENDIF()

  IF(NOT DEFINED CMAKE_SHARED_LIBRARY_SONAME_JavaC_FLAG)
    SET(CMAKE_SHARED_LIBRARY_SONAME_JavaC_FLAG ${CMAKE_SHARED_LIBRARY_SONAME_C_FLAG})
  ENDIF()

  # repeat for modules
  IF(NOT CMAKE_SHARED_MODULE_CREATE_JavaC_FLAGS)
    SET(CMAKE_SHARED_MODULE_CREATE_JavaC_FLAGS ${CMAKE_SHARED_MODULE_CREATE_C_FLAGS})
  ENDIF(NOT CMAKE_SHARED_MODULE_CREATE_JavaC_FLAGS)

  IF(NOT CMAKE_SHARED_MODULE_JavaC_FLAGS)
    SET(CMAKE_SHARED_MODULE_JavaC_FLAGS ${CMAKE_SHARED_MODULE_C_FLAGS})
  ENDIF(NOT CMAKE_SHARED_MODULE_JavaC_FLAGS)

  IF(NOT CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG)
    SET(CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG ${CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG})
  ENDIF(NOT CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG)

  IF(NOT CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG_SEP)
    SET(CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG_SEP ${CMAKE_SHARED_LIBRARY_RUNTIME_JavaC_FLAG_SEP})
  ENDIF(NOT CMAKE_EXECUTABLE_RUNTIME_JavaC_FLAG_SEP)

  IF(NOT CMAKE_EXECUTABLE_RPATH_LINK_JavaC_FLAG)
    SET(CMAKE_EXECUTABLE_RPATH_LINK_JavaC_FLAG ${CMAKE_SHARED_LIBRARY_RPATH_LINK_JavaC_FLAG})
  ENDIF(NOT CMAKE_EXECUTABLE_RPATH_LINK_JavaC_FLAG)

  IF(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_JavaC_WITH_RUNTIME_PATH)
    SET(CMAKE_SHARED_LIBRARY_LINK_JavaC_WITH_RUNTIME_PATH ${CMAKE_SHARED_LIBRARY_LINK_C_WITH_RUNTIME_PATH})
  ENDIF(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_JavaC_WITH_RUNTIME_PATH)

  IF(NOT CMAKE_INCLUDE_FLAG_JavaC)
    SET(CMAKE_INCLUDE_FLAG_JavaC ${CMAKE_INCLUDE_FLAG_C})
  ENDIF(NOT CMAKE_INCLUDE_FLAG_JavaC)

  IF(NOT CMAKE_INCLUDE_FLAG_SEP_JavaC)
    SET(CMAKE_INCLUDE_FLAG_SEP_JavaC ${CMAKE_INCLUDE_FLAG_SEP_C})
  ENDIF(NOT CMAKE_INCLUDE_FLAG_SEP_JavaC)

  FOREACH(type SHARED_LIBRARY SHARED_MODULE EXE)
    IF(NOT CMAKE_${type}_LINK_STATIC_JavaC_FLAGS)
      SET(CMAKE_${type}_LINK_STATIC_JavaC_FLAGS
	${CMAKE_${type}_LINK_STATIC_C_FLAGS})
    ENDIF(NOT CMAKE_${type}_LINK_STATIC_JavaC_FLAGS)
    IF(NOT CMAKE_${type}_LINK_DYNAMIC_JavaC_FLAGS)
      SET(CMAKE_${type}_LINK_DYNAMIC_JavaC_FLAGS
	${CMAKE_${type}_LINK_DYNAMIC_C_FLAGS})
    ENDIF(NOT CMAKE_${type}_LINK_DYNAMIC_JavaC_FLAGS)
  ENDFOREACH(type)

endif()